### ISSUE TITLE
conflict onChange with scriptUrl

### ISSUE THREAD

**Issue by NugzarGaguliya** [codeslayer1/react-ckeditor#1]
when I add scriptUrl to props, onChange doesn't triggers. If I remove scriptUrl component works fine.
I build ckeditor from builder tool. You can look for my build at http://app.dok32.com/ckeditor/ckeditor.js
Can you check why it doesn't works?

P.S. my build-config.js in same folder

P.P.S https://github.com/codeslayer1/react-ckeditor/blob/master/src/ckeditor.js#L49
this.editorInstance.on("change", ...) doesn't triggers

**Comment by codeslayer1** [comment]
Hi, did you find a fix? The onChange event triggers with both the default and custom build(built using builder tool)  that I have used in my projects. Is this issue specific to your build? 

PS. You can pass your custom onChange event as props and add whatever handling is needed for your build.

**Comment by NugzarGaguliya** [comment]
Yes, I find it.
For some reason in standart build onChange plugin was disabled.
I add this plugin and then onChange event worked fine.
