### ISSUE TITLE
textColor and bgcolor are missing

### ISSUE THREAD

**Issue by lucasABTasty** [codeslayer1/react-ckeditor#12]
Hi, maybe It is just me who is missing something but I can't find the colors buttons in the toolbar. I tried with the toolbar configurator (https://ckeditor.com/latest/samples/toolbarconfigurator/index.html#basic), everything works just fine except the text and background color buttons. Is this a known issue ? How can I add them ? 

![image](https://user-images.githubusercontent.com/25525824/32339550-66f1ea0c-bff8-11e7-8e2a-02f223698319.png)

Thank you

**Comment by codeslayer1** [comment]
Hi,

These buttons are not included in the default build of CKEditor. You can create your own CKEditor build and add the colorbutton and colordialog plugin in your custom build. 

Then you can use your custom build as explained in the docs(and you can find that in closed issues as well. Using custom build has been discussed multiple times).

Here is the screenshot of my CKEditor after including these plugins. It works perfectly fine.
![screen shot 2017-11-03 at 4 49 51 pm](https://user-images.githubusercontent.com/11829647/32371590-6b0ea246-c0b7-11e7-81f1-80c1cc475220.png)
