### ISSUE TITLE
Add support for setting content state outside of an event listener

### ISSUE THREAD

**Issue by mikeLspohn** [codeslayer1/react-ckeditor#13]
I have a modal that have a list of text options with a `copy` button beside each. When you click the copy button it should take that takes and updates `content` which would render `CKEditor` with the correct content copied over showing. I have it wired up where onClick of the copy button updates editor content state, which works, but it doesn't update what the editor shows in the UI since it seems it only updates via one of the set eventListeners.

**Comment by codeslayer1** [comment]
Hi,

Events are used for listening to changes that happen inside CKEditor and take actions based on that. You cannot use it the other way to perform action on CKeditor instance from outside.

To change content inside your CKEditor from your parent component(modal in your case). You need to add a ref to it and then access the child functions. Here is an example.

1. Add ref like this to your CKEditor.
`<CKEditor
          ref={instance => {
            this.ckeditor = instance;
          }}
        />`

2. Now you can set data in your CKEditor like this. Simply call this method in your onClick of the copy button with new data. It will be reflected in your CKEditor.
`this.ckeditor.editorInstance.setData(yourData);`

Hope this solves your query.

**Comment by mikeLspohn** [comment]
Thanks, I actually figured it out shortly before reading this. That worked
fine!

**Comment by ramkrishna757575** [comment]
Hi, I tried using `this.ckeditor.editorInstance.setData(yourData);` however, it works for the first time and then it stops working. So I can see the data I set the first time, but after that, I don't see the next data I try to set. Could you please guide me with this. Thanks

**Comment by codeslayer1** [comment]
@ramkrishna757575 Can you please share your code? Its difficult to figure out anything without it.

**Comment by ramkrishna757575** [comment]
Sure...please have a look at it:

`class AddStartupModal extends React.Component {
    constructor(props) {
        super(props);
        this.handleModalClose = this.handleModalClose.bind(this);
        this.handleCKEditorChange = this.handleCKEditorChange.bind(this);
        this.handleStartupSelection = this.handleStartupSelection.bind(this);
        AddStartupModal.initState = AddStartupModal.initState.bind(this);
        this.state = AddStartupModal.initState();
    }

    static initState() {
        return {
            comment: ''
        };
    }

    componentDidUpdate(prevProps, prevState) {
        const {id} = this.props;
        if (!!id) {
            this.handleStartupSelection({value: id});
        }
    }

    handleModalClose() {
        const dispatch = this.props.dispatch;
        this.setState(AddStartupModal.initState());
        dispatch(actions.closeAddStartupModal());
    }

    handleStartupSelection(event) {
        if (!!event && !!event.value) {
            this.setState({selected_startup_id: event.value, loading_startup: true});
            axios.get(`API CALL HERE`)
                .then((response) => {
                    this.startupModalCkEditor.editorInstance.setData(response.data.comment);
                }, (error) => {
                    console.log('Error in api!!!')
                });
        }
    };

    handleCKEditorChange(event) {
        this.setState({comment: event.editor.getData()});
    }

    render() {
        return (
            <Modal show={showAddStartupModal} className={"addLeadManagerStartupModal"} modalSize="modal-lg">
                <div className="modal-header">
                    <h5 className="modal-title">Startup</h5>
                    <button type="button" className="close" onClick={this.handleModalClose} data-dismiss="modal"
                            aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>

                <div className="modal-body" style={{height: "430px", overflowY: "auto"}}>
                    <div className="d-sm-flex flex-sm-row">
                        <div className="d-sm-flex flex-sm-row">
                            <div className="p-2 align-self-center"><h5>Select a Startup from LV</h5></div>
                            <div className="p-2">
                                <Select.Async
                                    name="selectStartup"
                                    value={this.state.selected_startup_id}
                                    onChange={this.handleStartupSelection}
                                    loadOptions={debounce(getOptions, 300)}
                                />
                            </div>
                        </div>
                        <div className="p-2 full-width">
                            <CKEditor
                                ref={instance => {
                                    this.startupModalCkEditor = instance;
                                }}
                                activeClass="p10"
                                content={this.state.comment || ''}
                                events={{
                                    "change": this.handleCKEditorChange
                                }}
                            />
                        </div>
                    </div>
                </div>

                <div className="modal-footer">
                    <button type="button" className="btn btn-secondary" onClick={this.handleModalClose}>Cancel</button>
                    <button type="button" className="btn btn-primary">Save</button>
                </div>
            </Modal>
        )
    }
}`

**Comment by ramkrishna757575** [comment]
I tried changing the `handleStartupSelection` method and doing the setData in a setTimout callback with some delay and it work this way.

**Comment by codeslayer1** [comment]
Change your handleStartupSelection method to this once and see if it works. I think you may not be getting correct reference to startupModalCkEditor. Also see if you are getting any error in console. Because if it works with setTimeout, it should work any other way as well.

```
handleStartupSelection(event) {
    var that = this; //hold reference to this in that variable so that you can access startupModalCkEditor inside your api callback
    if (!!event && !!event.value) {
        axios.get(`API CALL HERE`)
            .then((response) => {
                that.startupModalCkEditor.editorInstance.setData(response.data.comment);
            }, (error) => {
                console.log('Error in api!!!')
            });
    }
};
```

**Comment by ramkrishna757575** [comment]
Sure will try that. Thanks
