### ISSUE TITLE
How to add plugin to CKEditor component

### ISSUE THREAD

**Issue by subbukarbyl** [codeslayer1/react-ckeditor#17]
I want to add Print button to editor toolbar, adding 'print' into toolbar configuration object isn't working.

**Comment by codeslayer1** [comment]
This has been discussed multiple times. Please refer these issues - #12  and #7

**Comment by subbukarbyl** [comment]
thanks. [#7](https://github.com/codeslayer1/react-ckeditor/issues/7) worked for me, but after uploading entire ckeditor build folder to the server I got print button.
