### ISSUE TITLE
Image File Browser

### ISSUE THREAD

**Issue by jmelendev** [codeslayer1/react-ckeditor#24]
Is there a way to utilize CKEditor plugins with this? For example i am looking for a way to browse the system for images to upload. CKEditor has plugins for that but how could I use those plugins, if possible?

**Comment by codeslayer1** [comment]
Yes. You can use plug-ins with this package. It has been discussed multiple times.

Please refer to these issues - #12 and #7

**Comment by jmelendev** [comment]
Excellent, much appreciated!
