### ISSUE TITLE
Module does not exists error.

### ISSUE THREAD

**Issue by bamne123** [codeslayer1/react-ckeditor#30]
![image](https://user-images.githubusercontent.com/10872173/37876355-c09208fe-3068-11e8-8b04-9f8735e22b8b.png)

**Comment by codeslayer1** [comment]
Are you trying to use this module with React Native? If yes, then I am not sure if it would work with React native because this module has specifically been built for React.

**Comment by bamne123** [comment]
@codeslayer1 I am using it in RN project. Can you provide solution for RN?

**Comment by codeslayer1** [comment]
Not sure about RN. Since RN doesn't render HTML so react-dom won't work with it. You can try to see the source code of this project and see if you can port it for RN. Can help you with the porting part in case you face any issues.

**Comment by codeslayer1** [comment]
Closing this issue since its unrelated to React.
