### ISSUE TITLE
Uncaught TypeError: this.setState is not a function

### ISSUE THREAD

**Issue by carlo-fontanos** [codeslayer1/react-ckeditor#34]
I get:  `Uncaught TypeError: this.setState is not a function` in my browser console when typing, 

I think it's referencing the `evt` as `this`.

**Comment by carlo-fontanos** [comment]
Hi, 

Please see code bellow:

`import React, { Component } from 'react';
import CKEditor from "react-ckeditor-component";

export default class ItemCreate extends Component {
    constructor(props) {
		super(props);
        this.state = {
            is_loading: false,
            data_single: null,
            content: null
		}
        
	}
    
    onChange(evt){
        this.setState({content: evt.editor.getData()});
        // console.log(evt.editor.getData());
    }
    
    render() {
        return (
            <div className="col-md-6 col-md-offset-3 ml-t">
                <div className="clearfix">
                    <div className="col-md-12">
                        <div className="box ml-t">
                            <div className="form-group">
                                <label htmlFor="title">What are you selling or offering?:</label>
                                <input type="text" id="title" name="title" className="form-control" />
                            </div>
                            <div className="form-group">
                                <label htmlFor="price">Description:</label>
                                <CKEditor 
                                    content={""} 
                                    events={{
                                        "change": this.onChange
                                    }}
                                />
                            </div>
                            
                            <input type="submit" className="btn btn-default" />
                        </div>
                    </div>
                </div>
            </div>
        );
    }
}`

**Comment by codeslayer1** [comment]
This does not seem to be an error with the component. Looks like in your onChange method, you do not have access to `this`. You must bind `this` to your onChange function. To do this, add this line in your constructor.

```
this. onChange = this. onChange.bind(this);
```
See if this helps.

**Comment by carlo-fontanos** [comment]
Thank you, your solution worked for me!

**Comment by codeslayer1** [comment]
Welcome. Closing this issue.

**Comment by Abhinash1994** [comment]
I get: simple problem but i don't know how can i solve it. when i will submit the ckeditor then i got with html tag the my content . 

like <p> what's up?</p>
