### ISSUE TITLE
State not loaded with nginx and redux form

### ISSUE THREAD

**Issue by shaggyrec** [codeslayer1/react-ckeditor#5]
I interact with redux-form. When I set the default state from the Redux-forms, it does not working if file of editor cached by browser

```
class renderCKEditor extends React.Component {
  constructor(props) {
    super(props)
    const {value} = props.input
    this.updateContent = this.updateContent.bind(this)
    this.setContent = this.setContent.bind(this)
    this.state = {
      content: value
    }
  }

  componentDidMount() {
    const {value} = this.props.input
    this.setContent(value)
  }

  componentDidUpdate(prevProps, prevState) {
    const {value} = this.props.input;
    const {content} = this.state
    if ((!content || content === '<p><br></p>') && value && !prevProps.value) {
      this.setContent(value)
    }
  }

  setContent(newContent) {
    this.setState({
      content: newContent
    })
  }

  updateContent(newContent) {
    const {onChange} = this.props.input
    onChange(newContent)
    this.setContent(newContent)
  }

  render() {
    const {label, input, meta: {touched, error, invalid, warning}} = this.props
    return (
      <div className='form-group'>
        <label className="control-label">{label}</label>
        <CKEditor activeClass="p10" content={this.state.content} scriptUrl='/app/ckeditor/ckeditor.js'
                  onChange={this.updateContent}/>
        <hr/>
        <div className="help-block">
          {touched && ((error && <span>{error}</span>) || (warning && <span>{warning}</span>))}
        </div>
      </div>
    )
  }
}
```

**Comment by shaggyrec** [comment]
but if it add other fields they work...

**Comment by codeslayer1** [comment]
Are you getting any error in console? And by not working, do you mean to say that the default content is not getting set in CKEditor window? And does it gets set when the script is not cached?

**Comment by shaggyrec** [comment]
No errors in console.
Yes? editor is working, but content no getting in window.
When script not cached, it works good

**Comment by codeslayer1** [comment]
Can you create a JS fiddle / working example for your code? Or if you have TeamViewer, I can look into your machine because I am not getting the problem clearly and its difficult to debug without seeing your actual redux store and the problem you are facing.

**Comment by shaggyrec** [comment]
let go teamViewer, fiddle is very difficult in this situation

**Comment by codeslayer1** [comment]
Sure. You can join my group here on Slack and ping me your TeamViewer details. https://goo.gl/QGyfyC

**Comment by codeslayer1** [comment]
@shaggyrec Closing this for now since this doesn't look an issue with the package but with the CKEditor version that you are using. Feel free to open it if you are able to dig in and find the reason for this issue.
