### ISSUE TITLE
Properties for disable CKEditor

### ISSUE THREAD

**Issue by bmd-eka** [codeslayer1/react-ckeditor#52]
hello, there are property for disable CKEditor ? There are not at your documentation

**Comment by codeslayer1** [comment]
Hi. Can you please describe what you wan't to achieve. Your issue is not clear.

**Comment by bmd-eka** [comment]
Hi, I mean how to make CKEditor readOnly ?

**Comment by codeslayer1** [comment]
Please check the existing issues before opening a new one. This has already been discussed recently. See this issue #51
