### ISSUE TITLE
Accept onBlur prop (or more generally, accept arbitrary hooks for CKEditor's 'on' method)

### ISSUE THREAD

**Issue by RobRendell** [codeslayer1/react-ckeditor#8]
It would be nice if we could hook additional events in the CKEditor such as "blur".

The simplest change would be to provide an additional prop, "onBlur", which you would handle much like you currently handle the onChange prop.

A more general approach would be to take an "events" prop akin to the current "config" prop, which would map various CKEditor event strings to callbacks, allowing something like:

            <CKEditor
                content={this.state.text}
                onChange={this.onChange}
                config={{
                    readOnly: this.props.readOnly,
                    ...this.props.config
                }}
                events={{
                    blur: this.onBlur
                }}
            />

If it's already possible to configure event handlers via config, I apologise - I'm not that familiar with CKEditor.

Also, apologies for abusing the Issues tracker to make a feature request.

Thank you for this handy react component!

**Comment by codeslayer1** [comment]
Hi Rob, Currently the library does not support custom events. Marking this issue as an enhancement. Will take this up soon and let you know once done. Thanks for suggesting the feature.

**Comment by codeslayer1** [comment]
Hey, This feature has been added in version v1.0.6. Please update to latest version from npm. Added an example in Readme as well on how to use the custom event listeners.

PS. The onChange event is now deprecated. Use events prop instead.

Closing this thread now. Feel free to open it again if you find any issues. In case of any other help, you can join me here on Slack - https://goo.gl/QGyfyC

**Comment by RobRendell** [comment]
Awesome work - thank you!

I haven't tried compiling it, but I think the example code in your README.md is missing a double curly bracket around the events prop.

         <CKEditor 
              activeClass="p10" 
              content={this.state.content} 
              events={
                "blur": this.onBlur,
                "afterPaste": this.afterPaste,
                "change": this.onChange
              }
         />
should be
         <CKEditor 
              activeClass="p10" 
              content={this.state.content} 
              events={{
                "blur": this.onBlur,
                "afterPaste": this.afterPaste,
                "change": this.onChange
              }}
         />

**Comment by codeslayer1** [comment]
Yup. Thanks for pointing it out. The example included in the package is correct and tested. I just missed the braces in README. Updated it.
